### ISSUE TITLE
Problems when changing properties while Acquisation is running

### ISSUE THREAD

**Issue by felixwanitschke** [pymmcore-plus/pymmcore-widgets#151]
On Windows
Installed Versions:
Micromanager: MMSetup_64bit_2.0.1_20230510
pymmcore: 10.3.0.71.0
pymmcore-plus: 0.6.7

I am using the device property table in a napari plugin to change the cameras properties. In this plugin, the Continuous Sequence Acquisition is basically running in the background all the time and changes can be applied to a camera

I ran into problems (freezing/crashes) when changing properties such as Binning or BitDepth while the Acquisation is running. I could solve this somehow by making changes to the _on_value_widget_change function (stopping the Acquisation...) :

```python
    def _on_value_widget_change(self, value: Any) -> None:
        if not self._updates_core:
            return
        try:
            self._mmc.setProperty(self._device_label, self._prop_name, value)
        except (RuntimeError, ValueError):
            # if there's an error when updating mmcore, reset widget value to mmcore
            try:
                self._mmc.stopSequenceAcquisition()
                self._mmc.setProperty(self._device_label, self._prop_name, value)
                self._mmc.startContinuousSequenceAcquisition()
            except:
                pass # could not stop acquisation
        finally:    

            real_value = self._mmc.getProperty(self._device_label, self._prop_name)
            self._value_widget.setValue(real_value)
``` 
This change made the crashes much less often. Is there another way to solve this, or how should I properly make changes to the cameras settings while Acquisation is running?

**Comment by fdrgsp** [comment]
Hi @felixwanitschke! I don't think micromanager has been designed with the possibility to change camera parameters while acquiring (exposure time aside). I would not wait for the `RuntimeError` error since I believe you cannot change camera parameters while `ContinuousSequenceAcquisition` is running. I would first check if a sequence is running like below:

```py
def _on_value_widget_change(self, value: Any) -> None:   
    ...
    if self._mmc.isSequenceRunning():
        self._mmc.stopSequenceAcquisition()

    self._mmc.setProperty(self._device_label, self._prop_name, value)
    self._mmc.startContinuousSequenceAcquisition()
    ...
```

and maybe also add `self._mmc.waitForDevice(self._mmc.getCameraDevice())` or `self._mmc.waitForSystem()` after stopping the acquisition sequence if sometimes you get an error.
